### ISSUE TITLE
error when i try create a job

### ISSUE THREAD

**Issue by labotsky** [ondrejbartas/sidekiq-cron#12]
when i try create a job in a console:
job = Sidekiq::Cron::Job.new( name: 'Hard worker - every 5min', cron: '*/5 \* \* \* *', klass: 'HardWorker')
job.valid? - false
job.errors - ["'cron' -> */5 \* \* \* *: uninitialized constant Rufus::Scheduler::CronLine"]
job.save - false
the same problem with in yml file

Help me

**Comment by anamba** [comment]
This issue has returned with rufus-scheduler 3.5.0.

https://github.com/jmettraux/rufus-scheduler/commit/5fad18cde687560bd85012efff226a65f5849f61

**Comment by PanfilovDenis** [comment]
+1

**Comment by tommyalvarez** [comment]
+1 same error with sidekiq 5.1.3 and sidekiq-cron 0.6.3 that uses rufus-scheduler 3.3.0

**Comment by coorasse** [comment]
@jmettraux why does a minor version change apis? shouldn't this have been released as 4.0.0?

**Comment by jmettraux** [comment]
Hello @coorasse,

wouldn't it be good if sidekiq-cron was doing `~> 3.3` instead of `>= 3.3.0` regarding its dependency on rufus-scheduler?

Could you please tell me exactly what goes wrong here?

I'm going with rufus-scheduler 3.5.0 instead of 4.0.0 because the API hasn't changed, rufus-scheduler 3.5.0 quacks like 3.4.0 does. Behind the scene, things have changed and if sidekiq-cron relies on internal details then I'd be glad to help as best as I can, a stack trace and a precise description of the problem would be appreciated.

Thanks in advance.

**Comment by jmettraux** [comment]
@anamba @coorasse And opening a new issue, with reference to this issue, would be better than hijacking an old, closed, issue.

Thanks in advance and best regards.

**Comment by jmettraux** [comment]
Actually, there is already an issue for that at https://github.com/ondrejbartas/sidekiq-cron/issues/199
