### ISSUE TITLE
does sidekiq-cron know how to handle multiple sidekiq processes and not mess up enqueuing? 

### ISSUE THREAD

**Issue by dbenjamin57** [ondrejbartas/sidekiq-cron#137]

**Comment by ondrejbartas** [comment]
Hi sidekiq cron can be used for applications which runs on multiple nodes or have more sideqk processes running.

The whole adding system is based on sorted set of redis which is used to determine that only first process who ask can enque job into queue. Any other process will as same sorted set and will get false, so they know that job was already enqueud for that time. 

Be aware that time is important for sidekiq cron so all servers should be synced with some global time provider. Then you will not face some problem which can occure (but this problem is over all for sidekiq, database etc...)
