### ISSUE TITLE
*Need Advice* Sidekiq jobs eat memory ! 

### ISSUE THREAD

**Issue by zauzaj** [ondrejbartas/sidekiq-cron#168]
I'd like to optimize my notification system, so here is how it works now:

Every time some change occurred on application, we're calling background job (Sidekiq) in order to compute some values and then to notify users via email.

This approach worked very well for a while, but suddenly we got memory leak as there were a lot of actions very frequently and we had about 30-50 workers per second so I need to refactor this.

What I would like to do is, instead of running worker immediately, to use `sidekiq-cron` scheduler but I'm afraid that also will cause a problem, but just "delayed" problem.

@ondrejbartas I'd like to hear from you if sidekiq-cron is good way for this or there is some other possible way to solve this issue? 

Thanks in advice !

**Comment by ondrejbartas** [comment]
Hi @zauzaj,
if you are having memory leak problem than most probably it is not caused by sidekiq or sidekiq-cron. 

I run both of them for long time without any issues. 

Ruby has problems with memory consumption, which basically do one thing, when it allocates some memory it will not flush it to system back when it does not need it anymore. 

I am running 2 sidekiq workers side by side, first worker is processing small actions with huge amount of workers and second worker process has only 1-2 workers and it is managing those huge imports or processes big data, by this I will ensure that I am not processing in one time more of these expensive workers. 

Does that makes sense for you?

**Comment by zauzaj** [comment]
Hi @ondrejbartas 

thanks a lot on your advice. That sounds very interesting, I will definitely try to implement something like that as it totally has sense :) 

Thanks again.
