### ISSUE TITLE
Can't find registered cron jobs

### ISSUE THREAD

**Issue by atitan** [ondrejbartas/sidekiq-cron#197]
Cron jobs are missing in the web UI.

After a few testings, I found that calling `Sidekiq::Cron::Job.all` will issue redis command `SMEMBERS sidekiq:cron_jobs` to find registered cron jobs.

However, `KEYS *` from Redis indicated that cron jobs are stored without `sidekiq:` prefix.

```
127.0.0.1:6379> smembers cron_jobs
1) "cron_job:sitemap_worker"
2) "cron_job:email_record_batcher"
```

I don't know if this is desired behavior or just something broken. Any idea?

My environment:
Sidekiq 5.1.3
Sidekiq-cron 0.6.3
Redis 4.0.8
Rails 5.1.6
Ruby 2.5.1

**Comment by tommyalvarez** [comment]
Did you requiered require 'sidekiq/cron/web'?

Moreover, did you include the following line inside the sidekiq.configure_server block?

`Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)`

If the answer to all is yes, try putting a byebug just above that line and manually execute it. If it returns an error complaining about rufus-scheduler it's because you have in your gemfile a version of rufus-scheduler 3.5.0 which is for the time being incompatible with sidekiq-cron and you need to downgrade it to 3.4.2 until someone solves the issue #199

**Comment by tommyalvarez** [comment]
@atitan did you try to byebug and manually execute the line i just told you? It may give you debug input at least.

**Comment by Kani999** [comment]
I have a similiar problem.

When I define in my initializer this line
  `config.redis = { url: Rails.application.config_for(:cable)['url'] }` 
for client and server, the jobs from `schedule.yml` will not appear.

When I comment out these lines, it works properly.
