### ISSUE TITLE
Rspec testing?

### ISSUE THREAD

**Issue by causztic** [ondrejbartas/sidekiq-cron#203]
Is there a way to test the cron jobs in rspec? sidekiq-rspec allows enqueuing into an array for the jobs but when I added their library the cron jobs still complained of Redis::CannotConnectError.

Any idea how to implement testing for sidekiq-cron? If I were to do a PR, where do I start?

**Comment by ondrejbartas** [comment]
@causztic thanks for question. I would start using redis in tests also, because it is another database like PG or MySQL. 

What I do in my rails application is that I add 
```
RSpec.configure do |config|
  config.before(:each) do
    Sidekiq.redis do |conn|
      con.flushdb!
    end
  end
end
```

which will ensure that before every test Sidekiq Redis database is clean and I can expect that I can play with sidekiq cron.

Btw in my applications I am not testing that SidekiqCron will enqueue jobs, I am testing workers/classes if they do what they suppose to do.

Did it help?

**Comment by causztic** [comment]
Thank you for the reply!
(https://github.com/philostler/rspec-sidekiq/wiki/FAQ-&-Troubleshooting)
rspec-sidekiq allows using of arrays for jobs queueing, is it currently possible for sidekiq-cron?

**Comment by ondrejbartas** [comment]
Ok, you will still need redis, (sidekiq cron is using it for some caching and storing information)

then you can do:

```
job = Sidekiq::Cron::Job.new(name: 'Hard worker - every 5min', cron: '*/5 * * * *', class: 'HardWorker')
```

you can test that job is valid:
`job.valid?`

and you can try to do
`job.test_and_enque_for_time! time`

this should add job into sidekiq queue (which can be than check by rspec-sidekiq)
btw it will add job only when given `time` matches cron notation.

Does it work for you like this?

**Comment by causztic** [comment]
thanks! I'll use redis for this.

**Comment by ziaulrehman40** [comment]
@ondrejbartas Do we have any dicumentation of `test_and_enque_for_time` method in specific? And testing sidekiq-cron in general?

I think there should be something about this in readme.
