### ISSUE TITLE
Cron Jobs not running

### ISSUE THREAD

**Issue by juand** [ondrejbartas/sidekiq-cron#22]
Hello, 

I'm currently running in to an issue where my cron jobs in a AWS environment are not running. My local box works perfectly fine! However, in AWS, i see the job scheduled in the sidekiq-cron tab, but i don't see any trace of the jobs getting executed. Not in the logs or in the job queue, or even reflected on the admin tab (last enqueued remains unchanged). I

t just seems like no worker is actually executing anything and I don't know if this is a setup issue, an environment issue since there doesn't seem to be any trace of any attempts to run it or any errors when loading up the environment.

Any help would be greatly appreciated

This is my setup: 

**Gemfile**

```
gem 'sidekiq', '2.17.7'
gem 'sidekiq-failures', '0.4.3'
gem "sidekiq-cron", "~> 0.2.0"
```

**Gemfile.lock**

```
    sidekiq (2.17.7)
      celluloid (>= 0.15.2)
      connection_pool (>= 1.0.0)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    sidekiq-cron (0.2.0)
      rufus-scheduler (>= 2.0.24)
      sidekiq (>= 2.17.3)
      tilt (< 2.0.0)
    sidekiq-failures (0.4.3)
      sidekiq (>= 2.16.0)
```

I'm loading the jobs in the initializer: 

```
  Sidekiq.configure_client do |config|
    config.redis = { :url => "redis://#{host}:#{port}/#{db}", :namespace => 'sidekiq'}
  end

  Sidekiq.configure_server do |config|
    config.redis = { :url => "redis://#{host}:#{port}/0", :namespace => 'sidekiq' }
  end

schedule_file = rails_root + "/config/sidekiq_schedule.yml"
if File.exists?(schedule_file)
  sidekiq_cron = YAML.load_file(schedule_file)
  Sidekiq::Cron::Job.load_from_hash sidekiq_cron[Rails.env]
end
```

**Comment by codeanpeace** [comment]
Reading through this issue was very helpful!

We're running Puma in clustered mode which does run forks and observed that our schedule.yml file was not being loaded once in a blue moon since `Sidekiq.server?` was returning false. The inconsistent nature of this complicated the debugging process and it wasn't until we added an else condition that we realized this was a timing issue.

@ondrejbartas Thoughts on updating the README.md to mention this explicitly in the "[Adding Cron job](https://github.com/ondrejbartas/sidekiq-cron#adding-cron-job)" section as well as mentioning Puma in the "[Forking Processes](https://github.com/ondrejbartas/sidekiq-cron#forking-processes)" section?
