### ISSUE TITLE
Jobs with same cron schedule running at the same time, even if they were added in different time

### ISSUE THREAD

**Issue by vifreefly** [ondrejbartas/sidekiq-cron#226]
Example:

First, I adding job with 5 minutes (`*/5 * * * *`) cron interval:
```ruby
job = Sidekiq::Cron::Job.new(name: "job_id_1", cron: "*/5 * * * *", class: "HardWorker", args: [id_1])
job.save
job.enque!
``` 

After 3 minutes I adding another job with a same interval (each 5 min):
```ruby
job = Sidekiq::Cron::Job.new(name: "job_id_2", cron: "*/5 * * * *", class: "HardWorker", args: [id_2])
job.save
job.enque!
``` 

I thought that these two jobs will be running each at it''s own schedule, like `job_id_1` runs, after 3 min runs `job_id_2`, then after another 2 min runs again `job_id_1`, then after another 3 min runs `job_id_2`, etc. 

BUT I found that jobs are actually running somehow at the same time each 5 mins, example:

```
2018-10-13T13:00:10.794Z 31851 TID-orxj5q7yn ParseJob JID-174af33036038343d34b5c8a INFO: start
2018-10-13T13:00:10.797Z 31851 TID-orxhghfyf ParseJob JID-4ac6da431702d9d57b231583 INFO: start
```

Is it a default behavior, bug, or can it be tweaked the way as I want? Thanks!

**Comment by jmettraux** [comment]
Hello,

this is the neither a bug, neither a default behaviour, it is the expected behaviour.

`*/5 * * * *` is equivalent to `0,5,10,15,20,25,30,35,40,45,50,55 * * * *`, see https://linux.die.net/man/5/crontab (`man 5 crontab`).

There is no concept of "scheduled at" involved. The crontab is read, the jobs are scheduled altogether.

If you want a gap between your two jobs, schedule them differently, `"*/5 * * * *"` for the first one, `"#{(0..57).step(5).collect { |t| t + 2 }.to_a.join(',')} * * * *"` for the second one.

If you fear an overlap between your two jobs, then use a mutex, if your setup spans multiple Ruby processes use some kind of database semaphore. If those solutions are not ok and you want your A before your B, then combine them in a single job scheduled at `*/5 * * * *`.

Best regards.

**Comment by vifreefly** [comment]
@jmettraux , got it! Many thanks for explanation
