### ISSUE TITLE
More often than one minute?

### ISSUE THREAD

**Issue by seban** [ondrejbartas/sidekiq-cron#26]
Is there a way to run scheduled job every 30 seconds?

**Comment by shaimr** [comment]
Is there a way to run it every 10 seconds?

**Comment by tmeinlschmidt** [comment]
*/30 * * * * * runs every 30 seconds, the same for */10 (notice number of *)
see https://github.com/jmettraux/rufus-scheduler/blob/master/lib/rufus/scheduler/cronline.rb#L67-L79

**Comment by ondrejbartas** [comment]
Yes it can run every 30 seconds, but you need to set `Sidekiq.poll_interval=10` and smaller (do not go under 1). 

Sidekiq uses separate thread for taking jobs from scheduled queue and putting them into normal queues. Sidekiq Cron is using same interval fo checking if job should be enqueued by comparing cron line and current time

**Comment by kaka-ruto** [comment]
@ondrejbartas please add this to the readme? Tekin has a PR for it here https://github.com/ondrejbartas/sidekiq-cron/pull/240

**Comment by beatak** [comment]
Those who like me, google `how to run sidekiq cron sub minute order`: A cron yaml like following should still work. Notice there are 6 stars, instead of 5, like [the comment above said](https://github.com/ondrejbartas/sidekiq-cron/issues/26#issuecomment-94818978).

```yaml
some_queue:
  class: SomeWorker
  cron: '*/10 * * * * * America/Los_Angeles'
  args:
    foo: 100
```

BUT! `Sidekiq.poll_interval = 10` is long gone ([by v3.4.0, which was in 2015](https://github.com/mperham/sidekiq/commit/149949373fe371a3c2c60a7f7c5984317762d811))

So instead, you should do as follows. This is in `config/initializers/sidekiq.rb` in a typical Rails project. ([Link to the source](https://github.com/mperham/sidekiq/blob/main/lib/sidekiq.rb#L221-L228))

```ruby
Sidekiq.configure_server do |config|
  config.average_scheduled_poll_interval = 5
end
```
