### ISSUE TITLE
add TTL for redis keys

### ISSUE THREAD

**Issue by axos88** [ondrejbartas/sidekiq-cron#265]
Currently my redis is polluted with old, removed cron job data.

It would probably be a good idea to add a TTL for all the keys saved to redis (the cron job hashes and the :enqueued data). The TTL for the enqueued data could be refreshed on enqueueing and should be set to say 1.5x the REMEMBER_THRESHOLD, while the TTL for the cron jobs could be set to something relatively low (but the 1.5x REMEMBER_THRESHOLD could work too so it's uniform), as they would be recreated on the next startup anyways, and the TTL could be refreshed at every poll (or every 100th poll to reduce load).

Achtkually why do we even store the cron job hashes in redis at all?

**Comment by ondrejbartas** [comment]
@axos88 Sorry for responding you this late.

Sidekiq cron store cron jobs in redis because it can run concurrently on multiple machines. For example I am running 120 workers with 5+ threads each to maximize power of CPU on my machines. By this when I deploy my one worker all workers will know what to schedule.

Also many times it happens to my application that there are no restarts (startups) for many days, so than it could happen that my cron jobs will disappear by expiration of redis ke, which is undesired behaviour.
