### ISSUE TITLE
Jobs not scheduled after changing number of dynos

### ISSUE THREAD

**Issue by gleseur** [ondrejbartas/sidekiq-cron#301]
Hi,

We're using Heroku and regularly change the number of dynos running Sidekiq depending on current load.
We're using the following version:

Sidekiq 5.2.5
sidekiq-pro 4.0.4
sidekiq-cron 1.1.0
redis 3.3.5

We've noted the following behavior:
It can happen that when shutting down workers, some jobs are no longer scheduled while they should until we restart the dynos or start new ones.
It looks like this happens when the dyno running the job is the one shut down. Then on restart superfetch will pop the job and the cron scheduling will resume.

Can we do something about this ?
It makes the cron fairly unreliable.

Thanks,

**Comment by ondrejbartas** [comment]
@gleseur problem you are facing is due to way how sidekiq-cron works. It will start scheduling jobs when at least 1 sidekiq worker/process is running. 

When you downscale/upscale your worker is not running so there is no way to schedule jobs  :/ 

there is one possible solution for it - can you run separate small dyno which will ensure that your sidekiq process is runnig?

**Comment by ondrejbartas** [comment]
btw this is smmiliar problem to #306
