### ISSUE TITLE
Cron jobs not being queued if the queue is quiet

### ISSUE THREAD

**Issue by jcostello** [ondrejbartas/sidekiq-cron#306]
In our deploy workflow we quiet the queues in order to prevent jobs to run in the middle of a deploy. This work nice for jobs triggered by the application but we found that a Cron job is never queued if the queue is quiet which makes it not to run after we finish the deploy. We expected to run after the queue goes out if quiet since the Cron time as recently passed. Is this behavior expected?

**Comment by ondrejbartas** [comment]
@jcostello when you are doing your deployment you will kill all sidekiq workers,this means that no worker is running so there is no sidekiq-cron running :/ whoch wil do exactly as you say. It will not enqueue any jobs. Because nothing is running :/

quiet or not it does not matter, Sidekiq-Cron is using same API of sidekiq to push jobs into redis when their time is right. 

I run multiple instances or sidekiq on multiple machines and I do rolling deploy, few will migrate to new version, few will remain on old and so on. By this I have allways at least one sidekiq running so my scheduler can add jobs to queues.

Did it help?

**Comment by Laykou** [comment]
@ondrejbartas Does this code https://github.com/ondrejbartas/sidekiq-cron/blame/master/lib/sidekiq/cron/launcher.rb#L28-L31 mean that the cron poller is terminated when Sidekiq process is quiet?
