### ISSUE TITLE
Multiple jobs scheduled at the same time

### ISSUE THREAD

**Issue by spinx** [ondrejbartas/sidekiq-cron#81]
Hi,

We have 2 worker servers running Sidekiq. We added sidekiq-cron and it's adding multiple exactly the same jobs at once. 

Its adding 2-4 jobs at the same time. 

using Sidekiq 4.0.1

Any ideas why this happens ?

**Comment by jonmchan** [comment]
I've encountered the same issue. I'm running 2 different worker servers and I'm getting 2 jobs running at the same time when the job is fired.

I'm on Sidekiq v3.3.4.

**Comment by ondrejbartas** [comment]
Hié I know where is the problem :(

my bad in thinking. I will creat PR asap

**Comment by ondrejbartas** [comment]
@jonmchan @spinx this is strange I was going through code of enqueue and find out that there should be no edge case for sidekiq cron to enqueue 1 job more than 1 time. Thing is how sidekiq cron is adding jobs and this is done by inserting enqueue time into sorted set in redis which is returning `true` for new insertion and `false` for updating. Because redis has all commands atomit, there should be only 1 enqueue at a time (I am using it in production for more than two years without problems). ONe thing can be problematic if you have two redis instances, by this you will get 2 jobs enqueued becasue sidekiq cron is looking into separate redises. Can be this your case?

**Comment by masterkain** [comment]
I flushed everything in redis in production, started two sidekiq processes on 3 different instances, I got 4 of the same job enqueued and running at the same time.

**Comment by ondrejbartas** [comment]
@masterkain pls try this new version `0.4.2`

**Comment by bshyong** [comment]
hey guys I see this problem too; could it possibly be caused by concurrency issues? A sidekiq worker has 25 threads by default.

**Comment by snovity** [comment]
Having the same problem with sidekiq-cron 0.4.2 and sidekiq 4.0.2. Job is being enqueued 6 times even when I have left only one sidekiq process with one thread. Maybe this has something to do with unicorn?

**Comment by snovity** [comment]
Turns out in my case the problem was with cron notation, I used `* */30 * * * *` which means every half our but at any second. And what was happening, is that every half an our it would hit 6 times during one minute (because of 10 second sidekiq-cron polling interval). After I changed to `0 */30 * * * *` everything was solved.

**Comment by ondrejbartas** [comment]
@bshyong do you still have this issue?

**Comment by bshyong** [comment]
@ondrejbartas I think it's good now, thanks

**Comment by hiteshkanwar** [comment]
Hi,

running cron for every 15 minute like this * /15 * * * * but it fired 5 times after 15 minute,
Also running Another worker for every 30 mintue but fired after one hour
Can you suggest me how i run cron every 15 min and 30 min or every day

**Comment by hgani** [comment]
@hiteshkanwar try the solution described by @snovity above

I.e. 0 */15 * * * *

For 30 min, should be: 0 */30 * * * *
